name: browser_controller
version: 0.00.2-dev
authors: ["Dart Team <misc@dartlang.org>"]
homepage: http://www.dartlang.org
description: >
 Package for browser test automation. 
dependencies:
  path: ">=1.0.0 <2.0.0"
  args: ">=0.10.0+1 <0.10.1"
environment:
  sdk: ">=1.2.0 <2.0.0"
